import { describe, it, expect } from 'vitest';
import { transformEntries } from './commandMessage';
import type { ConversationEntry } from './transcript';

const CAVEAT =
  '<local-command-caveat>Caveat: The messages below were generated by the user ' +
  'while running local commands. DO NOT respond to these messages or otherwise ' +
  'consider them in your response unless the user explicitly asks you to.</local-command-caveat>';

describe('transformEntries', () => {
  it('rewrites a slash command into a compact command entry', () => {
    const input: ConversationEntry[] = [
      {
        role: 'user',
        text: '<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>',
        timestamp: 1,
      },
    ];
    const [cmd] = transformEntries(input);
    expect(cmd).toEqual({ role: 'command', name: '/clear', args: undefined, stdout: undefined, timestamp: 1 });
  });

  it('captures non-empty command args', () => {
    const input: ConversationEntry[] = [
      {
        role: 'user',
        text: '<command-name>/effort</command-name>\n<command-args>ultracode</command-args>',
        timestamp: 2,
      },
    ];
    const [cmd] = transformEntries(input);
    expect(cmd).toMatchObject({ role: 'command', name: '/effort', args: 'ultracode' });
  });

  it('folds a standalone stdout block into the preceding command', () => {
    const input: ConversationEntry[] = [
      { role: 'user', text: '<command-name>/effort</command-name>\n<command-args></command-args>', timestamp: 3 },
      {
        role: 'user',
        text: '<local-command-stdout>Set effort level to ultracode (this session only)</local-command-stdout>',
        timestamp: 3,
      },
    ];
    const out = transformEntries(input);
    expect(out).toHaveLength(1);
    expect(out[0]).toMatchObject({
      role: 'command',
      name: '/effort',
      stdout: 'Set effort level to ultracode (this session only)',
    });
  });

  it('collapses caveat boilerplate into a system entry with inner text only', () => {
    const input: ConversationEntry[] = [{ role: 'user', text: CAVEAT, timestamp: 4 }];
    const [sys] = transformEntries(input);
    expect(sys.role).toBe('system');
    expect((sys as { text: string }).text).toContain('DO NOT respond');
    expect((sys as { text: string }).text).not.toContain('<local-command-caveat>');
  });

  it('passes through plain user / assistant / tool entries untouched', () => {
    const input: ConversationEntry[] = [
      { role: 'user', text: 'enhance the PDF reader', timestamp: 5 },
      { role: 'assistant', text: "I'll start by looking", timestamp: 6 },
      { role: 'tool_use', tool: 'Read', input: '/tmp/x.png', timestamp: 7 },
    ];
    expect(transformEntries(input)).toEqual(input);
  });

  it('renders a stdout block with no preceding command as its own system entry', () => {
    const input: ConversationEntry[] = [
      { role: 'assistant', text: 'done', timestamp: 8 },
      { role: 'user', text: '<local-command-stdout>orphan output</local-command-stdout>', timestamp: 9 },
    ];
    const out = transformEntries(input);
    expect(out[1]).toEqual({ role: 'system', text: 'orphan output', timestamp: 9 });
  });
});
