import { describe, it, expect } from 'vitest';
import { transformEntries, classifyInjection } from './commandMessage';
import type { ConversationEntry } from './transcript';

const CAVEAT =
  '<local-command-caveat>Caveat: The messages below were generated by the user ' +
  'while running local commands. DO NOT respond to these messages or otherwise ' +
  'consider them in your response unless the user explicitly asks you to.</local-command-caveat>';

describe('transformEntries', () => {
  it('rewrites a slash command into a compact command entry', () => {
    const input: ConversationEntry[] = [
      {
        role: 'user',
        text: '<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>',
        timestamp: 1,
      },
    ];
    const [cmd] = transformEntries(input);
    expect(cmd).toEqual({ role: 'command', name: '/clear', args: undefined, stdout: undefined, timestamp: 1 });
  });

  it('captures non-empty command args', () => {
    const input: ConversationEntry[] = [
      {
        role: 'user',
        text: '<command-name>/effort</command-name>\n<command-args>ultracode</command-args>',
        timestamp: 2,
      },
    ];
    const [cmd] = transformEntries(input);
    expect(cmd).toMatchObject({ role: 'command', name: '/effort', args: 'ultracode' });
  });

  it('folds a standalone stdout block into the preceding command', () => {
    const input: ConversationEntry[] = [
      { role: 'user', text: '<command-name>/effort</command-name>\n<command-args></command-args>', timestamp: 3 },
      {
        role: 'user',
        text: '<local-command-stdout>Set effort level to ultracode (this session only)</local-command-stdout>',
        timestamp: 3,
      },
    ];
    const out = transformEntries(input);
    expect(out).toHaveLength(1);
    expect(out[0]).toMatchObject({
      role: 'command',
      name: '/effort',
      stdout: 'Set effort level to ultracode (this session only)',
    });
  });

  it('collapses caveat boilerplate into a system entry with inner text only', () => {
    const input: ConversationEntry[] = [{ role: 'user', text: CAVEAT, timestamp: 4 }];
    const [sys] = transformEntries(input);
    expect(sys.role).toBe('system');
    expect((sys as { text: string }).text).toContain('DO NOT respond');
    expect((sys as { text: string }).text).not.toContain('<local-command-caveat>');
  });

  it('passes through plain user / assistant / tool entries untouched', () => {
    const input: ConversationEntry[] = [
      { role: 'user', text: 'enhance the PDF reader', timestamp: 5 },
      { role: 'assistant', text: "I'll start by looking", timestamp: 6 },
      { role: 'tool_use', tool: 'Read', input: '/tmp/x.png', timestamp: 7 },
    ];
    expect(transformEntries(input)).toEqual(input);
  });

  it('renders a stdout block with no preceding command as its own system entry', () => {
    const input: ConversationEntry[] = [
      { role: 'assistant', text: 'done', timestamp: 8 },
      { role: 'user', text: '<local-command-stdout>orphan output</local-command-stdout>', timestamp: 9 },
    ];
    const out = transformEntries(input);
    expect(out[1]).toEqual({ role: 'system', text: 'orphan output', timestamp: 9, kind: 'plumbing' });
  });

  it('demotes an injected skill body to a labelled skill system row', () => {
    const skillText =
      'Base directory for this skill: /Users/kason/.claude/plugins/cache/superpowers/6.0.3/skills/systematic-debugging\n\n' +
      '# Systematic Debugging\n## Overview\nRandom fixes waste time.';
    const out = transformEntries([{ role: 'user', text: skillText, timestamp: 10 }]);
    expect(out[0]).toMatchObject({ role: 'system', kind: 'skill', label: 'systematic-debugging' });
  });

  it('detects the SessionStart skill-intro phrasing', () => {
    const intro =
      "Below is the full content of your 'superpowers:using-superpowers' skill - your introduction.";
    const out = transformEntries([{ role: 'user', text: intro, timestamp: 11 }]);
    expect(out[0]).toMatchObject({ role: 'system', kind: 'skill', label: 'superpowers:using-superpowers' });
  });

  it('demotes a leading system-reminder block', () => {
    const reminder = '<system-reminder>\nAs you answer the question, you can use the following context.\n</system-reminder>';
    const out = transformEntries([{ role: 'user', text: reminder, timestamp: 12 }]);
    expect(out[0]).toMatchObject({ role: 'system', kind: 'reminder' });
  });

  it('demotes injected hook additional-context', () => {
    const hook = '<EXTREMELY_IMPORTANT>\nYou have superpowers.\n</EXTREMELY_IMPORTANT>';
    const out = transformEntries([{ role: 'user', text: hook, timestamp: 13 }]);
    expect(out[0]).toMatchObject({ role: 'system', kind: 'hook' });
  });

  it('does NOT misclassify a genuine user prompt that merely mentions a skill', () => {
    const prompt = 'can you run the systematic-debugging skill on this? Base directory looks wrong.';
    const out = transformEntries([{ role: 'user', text: prompt, timestamp: 14 }]);
    expect(out[0]).toEqual({ role: 'user', text: prompt, timestamp: 14 });
  });

  it('classifyInjection returns null for genuine prompts and a kind for injections', () => {
    expect(classifyInjection('why are there previous trade records on the table?')).toBeNull();
    expect(classifyInjection('Base directory for this skill: /a/b/skills/foo-bar')).toEqual({
      kind: 'skill',
      label: 'foo-bar',
    });
  });
});
